import type { PublicMerchantResponse } from '@nook/contracts';

export const previewMerchant: PublicMerchantResponse = {
  slug: 'atelier-nook',
  name: '留白製甲所',
  category: 'NAIL',
  description:
    '在城市轉彎處的一人工作室。用低飽和色、細線與一點不對稱，替每一次伸手留下安靜但清楚的個性。',
  verificationStatus: 'UNVERIFIED',
  publishedAt: '2026-07-22T05:00:00.000Z',
  contact: { lineOaUrl: null, instagramUrl: 'https://www.instagram.com/' },
  location: {
    disclosure: 'DISTRICT_ONLY',
    name: null,
    address: null,
    postalCode: null,
    city: '台北市',
    district: '大安區',
    timezone: 'Asia/Taipei',
  },
  services: [
    {
      id: 'preview-service-1',
      name: '手部單色凝膠',
      description: '包含基礎保養、甲型修整與自選單色。',
      durationMinutes: 90,
      priceType: 'FIXED',
      priceAmount: 1200,
      priceMin: null,
      priceMax: null,
      currency: 'TWD',
    },
    {
      id: 'preview-service-2',
      name: '自由設計',
      description: '依當日靈感與你的日常，完成一組專屬設計。',
      durationMinutes: 150,
      priceType: 'FROM',
      priceAmount: 1800,
      priceMin: null,
      priceMax: null,
      currency: 'TWD',
    },
    {
      id: 'preview-service-3',
      name: '卸甲與深層保養',
      description: '溫和卸除、指緣整理與手部修護。',
      durationMinutes: 60,
      priceType: 'FIXED',
      priceAmount: 800,
      priceMin: null,
      priceMax: null,
      currency: 'TWD',
    },
  ],
  staff: [
    {
      id: 'preview-staff-1',
      displayName: 'Yun',
      bio: 'Nail artist / quiet detail collector',
      serviceIds: ['preview-service-1', 'preview-service-2', 'preview-service-3'],
    },
  ],
  weeklyHours: [{ weekday: 2, startTime: '11:00', endTime: '19:00' }],
  portfolio: [
    {
      id: 'preview-work-1',
      title: '煙灰色的午後',
      description: null,
      tags: ['霧面', '灰階'],
      imageUrl: '',
      thumbnailUrl: '',
    },
    {
      id: 'preview-work-2',
      title: '不對稱紅線',
      description: null,
      tags: ['線條', '朱紅'],
      imageUrl: '',
      thumbnailUrl: '',
    },
    {
      id: 'preview-work-3',
      title: '礦石與留白',
      description: null,
      tags: ['暈染', '透明感'],
      imageUrl: '',
      thumbnailUrl: '',
    },
  ],
  policies: {
    booking: '採完全預約制，請預留 10 分鐘抵達。',
    cancellation: '如需異動，請於預約時間 24 小時前聯繫。',
  },
  bookingAvailability: 'CANDIDATE_SLOTS',
};
