export const MERCHANT_PUBLICATION_REPOSITORY = Symbol('MERCHANT_PUBLICATION_REPOSITORY');
export const MARKETPLACE_MEDIA_SIGNER = Symbol('MARKETPLACE_MEDIA_SIGNER');
export const AVAILABILITY_REPOSITORY = Symbol('AVAILABILITY_REPOSITORY');
export const AVAILABILITY_CLOCK = Symbol('AVAILABILITY_CLOCK');
