export const APPOINTMENT_CONFIRMATION_REPOSITORY = Symbol('APPOINTMENT_CONFIRMATION_REPOSITORY');
export const APPOINTMENT_VIEW_REPOSITORY = Symbol('APPOINTMENT_VIEW_REPOSITORY');
export const APPOINTMENT_LIFECYCLE_REPOSITORY = Symbol('APPOINTMENT_LIFECYCLE_REPOSITORY');
