export const NOTIFICATION_PROJECTION_REPOSITORY = Symbol('NOTIFICATION_PROJECTION_REPOSITORY');
export const NOTIFICATION_DISPATCH_REPOSITORY = Symbol('NOTIFICATION_DISPATCH_REPOSITORY');
export const NOTIFICATION_TASK_GATEWAY = Symbol('NOTIFICATION_TASK_GATEWAY');
export const LINE_WEBHOOK_REPOSITORY = Symbol('LINE_WEBHOOK_REPOSITORY');
export const NOTIFICATION_DELIVERY_REPOSITORY = Symbol('NOTIFICATION_DELIVERY_REPOSITORY');
export const LINE_PUSH_CLIENT = Symbol('LINE_PUSH_CLIENT');
