export const PORTFOLIO_MEDIA_REPOSITORY = Symbol('PORTFOLIO_MEDIA_REPOSITORY');
export const MEDIA_UPLOAD_SIGNER = Symbol('MEDIA_UPLOAD_SIGNER');
export const MEDIA_VERIFICATION_QUEUE = Symbol('MEDIA_VERIFICATION_QUEUE');
